### PR TITLE
v0.3.1

### PR DESCRIPTION
**Pull request by giadarol**
**Minor fixes:**
 - Removed unnecessary function call
 - Allow beam-beam configuration with no LR (see issue #31)

### CODE REVIEW

**Comment by giadarol** [comment]
@sterbini If this is fine with you, it can be merged and deployed on AFS (no changes in the MAD-X parts)

**Comment by sterbini** [comment]
@giadarol This is fine with me. For the future versions I propose to add also the method in the ```madxp``` module of pymask. 

``` python
def knobs_df(my_df):
    '''
    Extract the knob list of a pandas DF (it assumes that DF has a column called "knobs")
    and contanting lists
    
    Args:
        my_df: a pandas DF (it assumes that DF has a column called "knobs").
    Returns:
        A data frame of knobs.
    
    See madxp/examples/variablesExamples/000_run.py
    '''
    import itertools
    import numpy as np
    aux= list(my_df['knobs'].values)
    aux= list(np.unique(list(itertools.chain.from_iterable(aux))))
    my_dict={}
    for i in aux:
        my_dict[i]={}
        filter_df=knob_df(i, my_df)
        my_dict[i]['multiplicity']=len(filter_df)
        my_dict[i]['dependences']=list(filter_df.index)
    return pd.DataFrame(my_dict).transpose().sort_values('multiplicity', ascending=False)
```
To get something similar to 
As for the variable and the element, we can naturally define the knobs of a sequence.



```python
mt.knobs_df(mt.sequence_df(mad, 'my_sequence'))
```





<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>multiplicity</th>
      <th>dependences</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>none</th>
      <td>3</td>
      <td>[my_sequence\$start, q1, my_sequence\$end]</td>
    </tr>
    <tr>
      <th>a</th>
      <td>1</td>
      <td>[q1]</td>
    </tr>
    <tr>
      <th>f</th>
      <td>1</td>
      <td>[q1]</td>
    </tr>
    <tr>
      <th>h</th>
      <td>1</td>
      <td>[q1]</td>
    </tr>
    <tr>
      <th>myk1</th>
      <td>1</td>
      <td>[q1]</td>
    </tr>
  </tbody>
</table>




For each knob you have the multiplicity, that is the number of elements are controlled by that specific knob. In the **dependences** column one have the explicit list of the elements controlled by this knob.

One can do also use the same function to extract of the knobs of the dependent variables.


```python
mt.knobs_df(my_variable_dict['dependent_variable_df'])
```





<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>multiplicity</th>
      <th>dependences</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>a</th>
      <td>2</td>
      <td>[b, c]</td>
    </tr>
    <tr>
      <th>f</th>
      <td>2</td>
      <td>[b, d]</td>
    </tr>
  </tbody>
</table>


It is a way to have  a clear inspection of the knob's use in the sequence. If you agree, I will prepare a merge pull request.

**Comment by giadarol** [comment]
> @giadarol This is fine with me. For the future versions I propose to add also the method in the `madxp` module of pymask.
> 
> ```python
> def knobs_df(my_df):
>     '''
>     Extract the knob list of a pandas DF (it assumes that DF has a column called "knobs")
>     and contanting lists
>     
>     Args:
>         my_df: a pandas DF (it assumes that DF has a column called "knobs").
>     Returns:
>         A data frame of knobs.
>     
>     See madxp/examples/variablesExamples/000_run.py
>     '''
>     import itertools
>     import numpy as np
>     aux= list(my_df['knobs'].values)
>     aux= list(np.unique(list(itertools.chain.from_iterable(aux))))
>     my_dict={}
>     for i in aux:
>         my_dict[i]={}
>         filter_df=knob_df(i, my_df)
>         my_dict[i]['multiplicity']=len(filter_df)
>         my_dict[i]['dependences']=list(filter_df.index)
>     return pd.DataFrame(my_dict).transpose().sort_values('multiplicity', ascending=False)
> ```
> 
> To get something similar to
> As for the variable and the element, we can naturally define the knobs of a sequence.
> 
> ```python
> mt.knobs_df(mt.sequence_df(mad, 'my_sequence'))
> ```
> 
> multiplicity	dependences
> none	3	[my_sequence\$start, q1, my_sequence\$end]
> a	1	[q1]
> f	1	[q1]
> h	1	[q1]
> myk1	1	[q1]
> For each knob you have the multiplicity, that is the number of elements are controlled by that specific knob. In the **dependences** column one have the explicit list of the elements controlled by this knob.
> 
> One can do also use the same function to extract of the knobs of the dependent variables.
> 
> ```python
> mt.knobs_df(my_variable_dict['dependent_variable_df'])
> ```
> 
> multiplicity	dependences
> a	2	[b, c]
> f	2	[b, d]
> It is a way to have a clear inspection of the knob's use in the sequence. If you agree, I will prepare a merge pull request.

@sternini , sure! I fully agree

**Comment by sterbini** [comment]
@giadarol

v0.3.1 deployed on ```afs```.

**Pull request merged**
